Section "Device"
    Identifier "Card0"
    Driver     "modesetting"
EndSection

Section "Monitor"
    Identifier "HDMI-1"
    ModeLine   "480x800" 30.00 480 528 576 656 800 810 820 914 -hsync +vsync
    Option     "PreferredMode" "480x800"
    Option     "Rotate"        "right"
EndSection

Section "Monitor"
    Identifier "HDMI-A-1"
    ModeLine   "480x800" 30.00 480 528 576 656 800 810 820 914 -hsync +vsync
    Option     "PreferredMode" "480x800"
    Option     "Rotate"        "right"
EndSection

Section "Screen"
    Identifier "Screen0"
    Device     "Card0"
    Monitor    "HDMI-1"
    SubSection "Display"
        Modes "480x800"
    EndSubSection
EndSection

