Section "InputClass"
    Identifier           "Cadwell abs evdev"
    MatchProduct         "Cadwell Laboratories, Inc. TouchScreen"
    MatchUSBID           "27c0:0859"
    MatchDevicePath      "/dev/input/event*"
    Driver               "evdev"
    Option "Ignore"      "off"
    Option "Mode"        "Absolute"
    Option "SwapAxes"    "off"
    Option "InvertX"     "off"
    Option "InvertY"     "off"
    Option "TransformationMatrix" "1 0 0 0 1 0 0 0 1"
EndSection
